const WeaponTypes="AssaultRifle SMG Shotgun LMG SniperRifle Carbine Special Staves Secondary Melee".split(" "),WeaponList=[{category:"AssaultRifle",name:"A-12 Plastic Rifle",value:"weird"},{category:"AssaultRifle",name:"AK Rifle",value:"cak"},{category:"AssaultRifle",name:"AVG Auto Rifle",value:"avg"},{category:"AssaultRifle",name:"Cilzret Fullauto",value:"Cilzret"},{category:"AssaultRifle",name:"Divine Long Bow",value:"divine"},{category:"AssaultRifle",name:"F44 Dominance",value:"Dominance"},{category:"AssaultRifle",
name:"FAZZI Automana",value:"fazzi"},{category:"AssaultRifle",name:"GEO Mana Rifle",value:"geo"},{category:"AssaultRifle",name:"Gerard Auto Rifle",value:"gerard"},{category:"AssaultRifle",name:"Golden AK[\u30d5\u30eb\u30aa\u30fc\u30c8]",value:"goldak"},{category:"AssaultRifle",name:"Golden AK[\u30bb\u30df\u30aa\u30fc\u30c8]",value:"goldak2"},{category:"AssaultRifle",name:"GROUZA",value:"groza"},{category:"AssaultRifle",name:"Hamlock AR",value:"hemlock"},{category:"AssaultRifle",name:"Harbinger Auto Rifle",
value:"harbinger"},{category:"AssaultRifle",name:"Hopekeeper",value:"hopekeeper"},{category:"AssaultRifle",name:"JAME Manaburst Rifle",value:"jame"},{category:"AssaultRifle",name:"Lexxi Burst Rifle",value:"lexxi"},{category:"AssaultRifle",name:"Luna Crossbow",value:"lunabow"},{category:"AssaultRifle",name:"M2002",value:"M2002"},{category:"AssaultRifle",name:"MDR",value:"MDR"},{category:"AssaultRifle",name:"MR-4 Smokey",value:"smokey"},{category:"AssaultRifle",name:"MR-4 Smokey EXT",value:"cu_smokey"},
{category:"AssaultRifle",name:"MR-12 Automana",value:"automana"},{category:"AssaultRifle",name:"MR-52 Cyclone",value:"cyclone"},{category:"AssaultRifle",name:"MR-55 Stormfury",value:"stormfury"},{category:"AssaultRifle",name:"MR-89 Doubletail",value:"Doubletail"},{category:"AssaultRifle",name:"MR-94 Gargoyle",value:"gargoyle"},{category:"AssaultRifle",name:"MRC-1 Silvermist",value:"Silvermist"},{category:"AssaultRifle",name:"NURF Water Rifle",value:"waterar"},{category:"AssaultRifle",name:"Ouroboros AR",
value:"ouro"},{category:"AssaultRifle",name:"Serenity Auto Rifle",value:"Serenity"},{category:"AssaultRifle",name:"Starfaller",value:"starfaller"},{category:"AssaultRifle",name:"The Shooting Star",value:"shootingstar"},{category:"AssaultRifle",name:"Twinvision Rifle",value:"twinvision"},{category:"AssaultRifle",name:"Type 89",value:"ctype"},{category:"AssaultRifle",name:"Tyrant Automana",value:"Tyrant"},{category:"AssaultRifle",name:"UDON-SKP Automana",value:"udon"},{category:"AssaultRifle",name:"VK-74 FLETLINE",
value:"fletline"},{category:"AssaultRifle",name:"Warewolf AR",value:"warewolf"},{category:"AssaultRifle",name:"Warmonger",value:"warmonger"},{category:"AssaultRifle",name:"WOUND Auto Rifle",value:"wound"},{category:"AssaultRifle",name:"XR-4 Auto Rifle",value:"xr4"},{category:"SMG",name:"Anarchy",value:"anarchy"},{category:"SMG",name:"Brawler Burst PDW",value:"brawler"},{category:"SMG",name:"Brigit, the bringer of flame",value:"Brigit"},{category:"SMG",name:"Demonflare",value:"demonflare"},{category:"SMG",
name:"Doorknocker",value:"door"},{category:"SMG",name:"Drumming Victory",value:"cu_victory"},{category:"SMG",name:"Envy",value:"Envy"},{category:"SMG",name:"FW-5 Azuris PDW",value:"azuris"},{category:"SMG",name:"Gabriel PDW",value:"Gabriel"},{category:"SMG",name:"GG36 SMG",value:"gg36"},{category:"SMG",name:"H.E.A.T 5",value:"heat5"},{category:"SMG",name:"Hystis 535",value:"Hystis"},{category:"SMG",name:"K92 Tiamat",value:"tiamat"},{category:"SMG",name:"K95 Basilisk",value:"Basilisk"},{category:"SMG",
name:"Lynn SMG",value:"lynn"},{category:"SMG",name:"Nox SMG",value:"nox"},{category:"SMG",name:"P9000 Mana PDW",value:"P9000"},{category:"SMG",name:"PP90N1 Dummy's",value:"pp90n1"},{category:"SMG",name:"Rogue's Shooter",value:"rogues"},{category:"SMG",name:"Silent Treatment",value:"Silent"},{category:"SMG",name:"The Bumblebee",value:"bumblebee"},{category:"SMG",name:"Thousand Cut",value:"thousand"},{category:"SMG",name:"Type6 Hicycle PDW",value:"type6"},{category:"SMG",name:"Victory",value:"victory"},
{category:"SMG",name:"VMT-2 Mice SMG",value:"vmt"},{category:"SMG",name:"Windmaker",value:"windmaker"},{category:"SMG",name:"X-1 Ammit",value:"Ammit"},{category:"SMG",name:"XS-5 Nether Beatle",value:"netherbeatle"},{category:"SMG",name:"XS-21 Pandora PDW",value:"pandora"},{category:"Shotgun",name:"AA122 Mana Shotgun",value:"aa12"},{category:"Shotgun",name:"Bazl's Blunderbuss",value:"bazl"},{category:"Shotgun",name:"Black Thunder",value:"blackThunder"},{category:"Shotgun",name:"Blondie[\u6563\u5f3e]",
value:"blond"},{category:"Shotgun",name:"Blondie[\u30d5\u30e9\u30b0]",value:"blond2"},{category:"Shotgun",name:"Crescent of Asha",value:"Asha"},{category:"Shotgun",name:"Crimson",value:"Crimson"},{category:"Shotgun",name:"E420 Hydra",value:"Hydra"},{category:"Shotgun",name:"F-85 The Raven",value:"raven"},{category:"Shotgun",name:"Gauss Rifle",value:"cgauss"},{category:"Shotgun",name:"Ghahr's Shotgun",value:"Ghahr"},{category:"Shotgun",name:"Howard's Double Barrel",value:"howard"},{category:"Shotgun",
name:"K-RAR Mana Splasher",value:"krar"},{category:"Shotgun",name:"LF-14 Auto Shotgun",value:"lf14"},{category:"Shotgun",name:"Lios Double Barrel",value:"lios"},{category:"Shotgun",name:"Lusha's Harp",value:"harp"},{category:"Shotgun",name:"M890 Beanshot",value:"m890"},{category:"Shotgun",name:"Ogrehunt",value:"ogrehunt"},{category:"Shotgun",name:"Ogrehunt Slug",value:"sogrehunt"},{category:"Shotgun",name:"OgreKiller",value:"cu_ogrehunt"},{category:"Shotgun",name:"Pianis Mana Splasher",value:"Pianis"},
{category:"Shotgun",name:"Pianis Mana Splasher Slug",value:"sPianis"},{category:"Shotgun",name:"Sabertooth Shotgun",value:"sabertooth"},{category:"Shotgun",name:"SG80 Evicserate",value:"evis"},{category:"Shotgun",name:"Spacemaker",value:"spacemaker"},{category:"Shotgun",name:"STUD Shotgun",value:"stud"},{category:"Shotgun",name:"The 1980",value:"1990"},{category:"Shotgun",name:"The Extra",value:"extra"},{category:"Shotgun",name:"The Thunder",value:"Thunder"},{category:"Shotgun",name:"Troublemaker Shotgun",
value:"trouble"},{category:"LMG",name:"Brutus MG",value:"Brutus"},{category:"LMG",name:"GILT Hypercycle LMG[\u9ad8\u30ec\u30fc\u30c8]",value:"gilt"},{category:"LMG",name:"GILT Hypercycle LMG[\u9ad8\u7cbe\u5ea6]",value:"gilt2"},{category:"LMG",name:"Gorgon 114 LMG",value:"Gorgon"},{category:"LMG",name:"Life Barrage Wand",value:"lifebarrage"},{category:"LMG",name:"M666 Spatfire",value:"spit"},{category:"LMG",name:"M757 Cleaner LMG",value:"M757"},{category:"LMG",name:"M9190 Beehive",value:"bee"},{category:"LMG",
name:"MG-80 Heavy Machinegun",value:"MG80"},{category:"LMG",name:"MK4 Machine Gun",value:"mk4"},{category:"LMG",name:"MK7 Baretooth",value:"baretooth"},{category:"LMG",name:"MK18 Leaf Cleaner",value:"leafcleaner"},{category:"LMG",name:"PBP-14",value:"PBP14"},{category:"LMG",name:"Silverstein MG",value:"silverstein"},{category:"LMG",name:"TT4 Nefaris LMG",value:"nefaris"},{category:"LMG",name:"TT4 Nefaris MMG",value:"cu_nefaris"},{category:"LMG",name:"\tTT66 Doom LMG",value:"TT666"},{category:"LMG",
name:"XL9 Mozer",value:"mozer"},{category:"SniperRifle",name:"Barnett the Deathbringer",value:"Barnett"},{category:"SniperRifle",name:"Car98k",value:"car98k"},{category:"SniperRifle",name:"Coldfang DMR",value:"Coldfang"},{category:"SniperRifle",name:"Colubrid .75 CAL",value:"colubrid"},{category:"SniperRifle",name:"Devil's Whisper",value:"devilswhisper"},{category:"SniperRifle",name:"EFX Photon Compressor",value:"photon"},{category:"SniperRifle",name:"Endseeker",value:"endseeker"},{category:"SniperRifle",
name:"ENT Sniper Rifle",value:"ent"},{category:"SniperRifle",name:"Flying Serpent",value:"flyingserpent"},{category:"SniperRifle",name:"Graveless DMR",value:"graveless"},{category:"SniperRifle",name:"Helheim DMR",value:"Helheim"},{category:"SniperRifle",name:"Horizon Rifle",value:"horizon"},{category:"SniperRifle",name:"Hunting Rifle",value:"chunt"},{category:"SniperRifle",name:"Ironbark Sniper Rifle",value:"ironbark"},{category:"SniperRifle",name:"Knightfall",value:"Knightfall"},{category:"SniperRifle",
name:"Lisrithe, Life and the Eternal Rest",value:"Lisrithe"},{category:"SniperRifle",name:"Lisrithe's Wish",value:"Lis2"},{category:"SniperRifle",name:"M850 Smogg Sniper Rifle",value:"smog"},{category:"SniperRifle",name:"Mark-7 EBR",value:"mark7"},{category:"SniperRifle",name:"Mellowwood",value:"mellowwood"},{category:"SniperRifle",name:"Minerva Anti-Matter Rifle",value:"minerva"},{category:"SniperRifle",name:"Moon Night",value:"moonnight"},{category:"SniperRifle",name:"Phobia SR-22",value:"phobia"},
{category:"SniperRifle",name:"Pierce Sniper Rifle",value:"pierce"},{category:"SniperRifle",name:"PMG H\u00e9kate \u2161",value:"hekate"},{category:"SniperRifle",name:"Rabbit Silencer",value:"Rabbitsilencer"},{category:"SniperRifle",name:"RSK Sniper Rifle",value:"rsk"},{category:"SniperRifle",name:"Shadowvein",value:"shadowvein"},{category:"SniperRifle",name:"Skullcrusher",value:"skullcrusher"},{category:"SniperRifle",name:"Skullcrusher QD",value:"cu_skullcrusher"},{category:"SniperRifle",name:"Syndra's Bow",
value:"syndra"},{category:"SniperRifle",name:"The Zomzeozy",value:"zom"},{category:"SniperRifle",name:"Third Eye DMR",value:"thirdeye"},{category:"SniperRifle",name:"Trueflight Bow",value:"true"},{category:"SniperRifle",name:"UDED Rail Rifle",value:"uded"},{category:"SniperRifle",name:"Wingmen",value:"wingmen"},{category:"Carbine",name:"Bayou Short Rifle",value:"Bayou"},{category:"Carbine",name:"Bayou Short Rifle[\u30a2\u30bf\u30c3\u30c1\u30e1\u30f3\u30c8]",value:"Bayou_at"},{category:"Carbine",name:"CARB-7",
value:"carb7"},{category:"Carbine",name:"CARB-7[\u30a2\u30bf\u30c3\u30c1\u30e1\u30f3\u30c8]",value:"carb7_at"},{category:"Carbine",name:"Chimaera CQB",value:"Chimaera"},{category:"Carbine",name:"Chimaera CQB[\u30a2\u30bf\u30c3\u30c1\u30e1\u30f3\u30c8]",value:"Chimaera_at"},{category:"Carbine",name:"ECR-11 Carbine",value:"ecr11"},{category:"Carbine",name:"ECR-11 Carbine[\u30a2\u30bf\u30c3\u30c1\u30e1\u30f3\u30c8]",value:"carb7_at"},{category:"Carbine",name:"Fiendsbreath Carbine",value:"fiendsbreath"},
{category:"Carbine",name:"Fiendsbreath Carbine[\u30a2\u30bf\u30c3\u30c1\u30e1\u30f3\u30c8]",value:"fiend_st"},{category:"Carbine",name:"Gritt Carbine",value:"Gritt"},{category:"Carbine",name:"Gritt Carbine[\u30a2\u30bf\u30c3\u30c1\u30e1\u30f3\u30c8]",value:"Gritt_at"},{category:"Carbine",name:"Hellhound Short Rifle",value:"hellhound"},{category:"Carbine",name:"Hellhound Short Rifle[\u30a2\u30bf\u30c3\u30c1\u30e1\u30f3\u30c8]",value:"hell_at"},{category:"Carbine",name:"Maelstrom Carbine",value:"Maelstrom"},
{category:"Carbine",name:"Maelstrom Carbine[\u30a2\u30bf\u30c3\u30c1\u30e1\u30f3\u30c8]",value:"maelstrom_at"},{category:"Carbine",name:"Maelstrom CQB",value:"cu_Maelstrom"},{category:"Carbine",name:"Maelstrom CQB[\u30a2\u30bf\u30c3\u30c1\u30e1\u30f3\u30c8]",value:"cu_maelstrom_at"},{category:"Carbine",name:"Shepherd 055",value:"Shepherd"},{category:"Carbine",name:"Shepherd 055[\u30a2\u30bf\u30c3\u30c1\u30e1\u30f3\u30c8]",value:"Shepherd_at"},{category:"Carbine",name:"Varg G5",value:"Varg"},{category:"Carbine",
name:"Varg G5[\u30a2\u30bf\u30c3\u30c1\u30e1\u30f3\u30c8]",value:"Varg_at"},{category:"Special",name:"AWR Gatling Laser",value:"awr"},{category:"Special",name:"Brugo Homing Missile",value:"Brugo"},{category:"Special",name:"F52 Ifrit Pigcooker",value:"ifrit"},{category:"Special",name:"F60 Ignis Firestarter",value:"ignis"},{category:"Special",name:"GL3 Handy Mortar",value:"mortar"},{category:"Special",name:"GL90 Warbringer",value:"warbringer"},{category:"Special",name:"GL 88 Carpet Bomber",value:"carpet"},
{category:"Special",name:"Golembreaker",value:"golembreaker"},{category:"Special",name:"Hi-K0 Launcher",value:"hikolaunch"},{category:"Special",name:"Hi-K0 Launcher[Stardust]",value:"2hikolaunch"},{category:"Special",name:"Hi-K0 Launcher 2021",value:"hiko2021"},{category:"Special",name:"HLL Magic Launcher",value:"HLL"},{category:"Special",name:"Jikill Sonic Launcher",value:"jikill"},{category:"Special",name:"Kali Magic Launcher",value:"kali"},{category:"Special",name:"Keg Bomb",value:"keg"},{category:"Special",
name:"Kerkox Mana Scroller",value:"Kerkox"},{category:"Special",name:"Love Launcher",value:"love"},{category:"Special",name:"MK20 Mana Waster",value:"minigun"},{category:"Special",name:"PKB-8004",value:"pkb"},{category:"Special",name:"Princess Crossbow",value:"princess"},{category:"Special",name:"Ragnis Rocket Launcher",value:"ragnis"},{category:"Special",name:"Rania's Chocolate Javelin",value:"javelin2"},{category:"Special",name:"Rania's Crossbow",value:"Rania"},{category:"Special",name:"Rania's Javelin",
value:"javelin"},{category:"Special",name:"Rubber Shuriken",value:"rubbershuriken"},{category:"Special",name:"S.O.L Rocket Launcher",value:"sol"},{category:"Special",name:"Spear of Judgement",value:"judgementspear"},{category:"Special",name:"T-X01 Anti-matter Missile",value:"antitank"},{category:"Special",name:"T-X Homing Nuke",value:"TX"},{category:"Special",name:"Tempest Grenade Launcher",value:"tempest"},{category:"Special",name:"The Bazooka",value:"cbazooka"},{category:"Special",name:"The Deathmachine",
value:"deathmachine"},{category:"Special",name:"The Eliminator",value:"eliminator"},{category:"Special",name:"TN-43 Remote TNT",value:"remote"},{category:"Special",name:"Trauma",value:"trauma"},{category:"Special",name:"Tigerhorse",value:"cu_trauma"},{category:"Special",name:"TX-500 Amber Cannon[\u76f4\u9032]",value:"amber"},{category:"Special",name:"TX-500 Amber Cannon[\u30db\u30fc\u30df\u30f3\u30b0]",value:"amber2"},{category:"Special",name:"Vateth Homing Missile",value:"Vateth"},{category:"Special",
name:"Vely's Party Cracker",value:"Velys"},{category:"Staves",name:"\u00c2coni, Fifth Element of the Arctic",value:"lame"},{category:"Staves",name:"\u00c2coni's Wistfulness[\u7a7a\u7206]",value:"lame21"},{category:"Staves",name:"\u00c2coni's Wistfulness[\u5c04\u6483]",value:"lame22"},{category:"Staves",name:"Arcane Bomb",value:"arcaneexplosion"},{category:"Staves",name:"Breir's Javelin",value:"breir"},{category:"Staves",name:"Enchanted Rod",value:"enchantedrod"},{category:"Staves",name:"Flame Rod",
value:"flamerod"},{category:"Staves",name:"Grim Reaper",value:"grimreaper"},{category:"Staves",name:"Ice Rod",value:"icerod"},{category:"Staves",name:"Kyugetu",value:"kyugetu"},{category:"Staves",name:"Nahhra, Devourer of Worlds",value:"Nahhra"},{category:"Staves",name:"Phantom Bolt",value:"Phantom"},{category:"Staves",name:"Pumpkin Wand",value:"pumpkinwand"},{category:"Staves",name:"Shadow Bolt",value:"cu_Phantom"},{category:"Staves",name:"Rod",value:"rod"},{category:"Staves",name:"Staff of Barrage",
value:"sob"},{category:"Staves",name:"Staff of Cursing",value:"soc"},{category:"Staves",name:"Staff of Eda",value:"eda"},{category:"Staves",name:"Staff of Elna",value:"soe"},{category:"Staves",name:"Staff of Glorious",value:"sog"},{category:"Staves",name:"Staff of Release",value:"sor"},{category:"Staves",name:"Staff of Sorrow",value:"sorrow"},{category:"Staves",name:"Staff of Spirit",value:"sos"},{category:"Staves",name:"Staff of Vesta",value:"Vesta"},{category:"Staves",name:"Staff of Zisca",value:"Zisca"},
{category:"Staves",name:"Worldender",value:"worldender"},{category:"Staves",name:"Yuki Kaze",value:"yuki"},{category:"Secondary",name:"Alien Phaser",value:"alienpistol"},{category:"Secondary",name:"Alpha Phaser",value:"alphaphaser"},{category:"Secondary",name:"Arda Sure Shot",value:"arda"},{category:"Secondary",name:"Aries",value:"aries"},{category:"Secondary",name:"Arizona",value:"arizona"},{category:"Secondary",name:"Beta Phaser",value:"betaphaser"},{category:"Secondary",name:"Book of Mother Earth",
value:"bookofmother"},{category:"Secondary",name:"Desert Falcon",value:"desertfalcon"},{category:"Secondary",name:"Desertdog MMG",value:"Desertdog"},{category:"Secondary",name:"Desolation",value:"deso"},{category:"Secondary",name:"Eclipse",value:"Eclipse"},{category:"Secondary",name:"Forty Three Pistol",value:"43"},{category:"Secondary",name:"G7 Self Defence",value:"g7"},{category:"Secondary",name:"Gadrec's Sawed-off",value:"gadrec"},{category:"Secondary",name:"GL1 Grenade Shooter",value:"GL1"},{category:"Secondary",
name:"GL4 Compact Launcher",value:"GL4"},{category:"Secondary",name:"GL99 Micro Missile Launcher",value:"gl99"},{category:"Secondary",name:"Golden One",value:"goldenone"},{category:"Secondary",name:"Golden TK[\u901a\u5e38]",value:"goldtk"},{category:"Secondary",name:"Golden TK[\u30b5\u30a4\u30ec\u30f3\u30b5\u30fc]",value:"goldtk2"},{category:"Secondary",name:"Golden West",value:"gold"},{category:"Secondary",name:"Golden West 2022",value:"gold2"},{category:"Secondary",name:"H1 Goblin Hunter",value:"goblin"},
{category:"Secondary",name:"Harden's Blunderbuss",value:"Harden"},{category:"Secondary",name:"Joker",value:"joker"},{category:"Secondary",name:"Karc-8",value:"Karc"},{category:"Secondary",name:"Limewillow",value:"limewillow"},{category:"Secondary",name:"Lonewolf",value:"lonewolf"},{category:"Secondary",name:"Loveling\u2665",value:"lovelove"},{category:"Secondary",name:"M-P4 Battlecraft Pistol",value:"battlecraft"},{category:"Secondary",name:"Modernbick Shotgun",value:"modern"},{category:"Secondary",
name:"Moria Nagan",value:"morianagan"},{category:"Secondary",name:"N1 Hidden Gun",value:"hiddengun"},{category:"Secondary",name:"Old West",value:"oldwest"},{category:"Secondary",name:"Old West Fanning Shot",value:"oldf"},{category:"Secondary",name:"Old West Triple Action",value:"old3"},{category:"Secondary",name:"P5 Auto Pistol",value:"p5"},{category:"Secondary",name:"P77 Quad Action",value:"quadaction"},{category:"Secondary",name:"P-20 Stormcaller",value:"stormcaller"},{category:"Secondary",name:"PocketCannon",
value:"pocketcannon"},{category:"Secondary",name:"Quickcleave",value:"Quickcleave"},{category:"Secondary",name:"Red Mongoose",value:"redmongoose"},{category:"Secondary",name:"Silver Old West",value:"olds"},{category:"Secondary",name:"Sixfinger",value:"sixfinger"},{category:"Secondary",name:"Sling Shot",value:"demonpower"},{category:"Secondary",name:"TC5 Magicka",value:"tc5"},{category:"Secondary",name:"The Etna",value:"etna"},{category:"Secondary",name:"UZH Portable SMG",value:"uzh"},{category:"Secondary",
name:"Vunnaq",value:"vunna"},{category:"Secondary",name:"Vunnaq Fullauto",value:"vunnaf"},{category:"Secondary",name:"Wandrak Hand Cannon",value:"wardrak"},{category:"Secondary",name:"Water Pistol",value:"waterpistol"},{category:"Secondary",name:"Wildville \u201875",value:"Wildville"},{category:"Secondary",name:"",value:"thetester"},{category:"Secondary",name:"",value:"thetester2"},{category:"Melee",name:"Aodhlugh, Creator of Volcanoes",value:"Aodhlugh"},{category:"Melee",name:"Az'gan, The matter of darkness[\u8fd1\u63a5]",
value:"azz"},{category:"Melee",name:"Az'gan, The matter of darkness[\u5c04\u6483]",value:"azz_at"},{category:"Melee",name:"Bloody Axe",value:"bloodyaxe"},{category:"Melee",name:"Broken Dahlia",value:"dahlia"},{category:"Melee",name:"Cultist Knife",value:"cultist"},{category:"Melee",name:"Gravity Axe",value:"gravity"},{category:"Melee",name:"kanabou",value:"kanabou"},{category:"Melee",name:"Manablade",value:"manablade"},{category:"Melee",name:"Mine Uchi",value:"mineuchi"},{category:"Melee",name:"Ninja Kunai",
value:"kunai"},{category:"Melee",name:"Nyr, Thunderblade of Oath Keeper",value:"Nyr"},{category:"Melee",name:"SA-SA",value:"sasa"},{category:"Melee",name:"Shadowfang",value:"Shadowfang"},{category:"Melee",name:"StarBlade",value:"starblade"},{category:"Melee",name:"Sword of Faith",value:"swordoffaith"},{category:"Melee",name:"The Brute",value:"Brute"},{category:"Melee",name:"The Punisher",value:"punisher"},{category:"Melee",name:"Valhalla",value:"Valhalla"},{category:"Melee",name:"Warblade of Thanatos",
value:"thanatos"},{category:"Melee",name:"Windsong Polearm",value:"Windsong"},{category:"Melee",name:"Witch's Broom",value:"broom"},{category:"Melee",name:"Xeg'then, Initiator of Sundown",value:"xeg"},{category:"Melee",name:"Zan Getsu",value:"zangetsu"}],Sunfire=[3,.67,.72,.77,0],DemonPower=[4,.35,.4,.45,0],SiphonLife=[2,.4,.5,.6,0],DeathsRuin=[6,.55,.6,.65,.15],ArcaneBrilliance=[3,.35,.45,.55,.2],NorthernWind=[5,.45,.5,.55,.1],FlexibleResonance=[4,.65,.7,.75,0],PhoenixFlame=[10,.05,.06,.07,0],ShadowStrike0=
[6,.7,.75,.8,0],ShadowStrike1=[2,.7,.75,.8,0],ShadowStrike2=[2,.4,.45,.5,0],BcDmg=7,EoDmg=6,McDmg=1,CfDmg=4,MbDmg=5,WsDmg=2,SdAverageDmg=1,SdHighestDmg=20,MflDmg0=1,MflDmg1=2,MflDmg2=3,EodDmg=100,Result=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],Weapon=[0,0,0,0,0,0,0,0,0,0,0],Mod=[0,0,0,0,0,0,0,0],EnchDmg=[0,0,0,0,0,0],Ae=[0,0,0],Addon=[0,0,0,0,0,1],EnchActive=[0,0],MpDmg=[.25,.5,1,1.5],HbAverageDmg=[.4,.8,1.2,1.6],HbHighestDmg=[2,4,6,8],EmCapacity=[2,4,6,10],QpReload=[-4,-8,-12,-16],LkWeight=[.004,
.005,.01,.015],SsaDmg=[1.25,1.5,1.75,2.2],SbDmg=[7,8,9,10],_pathAr="maps/1_AR.json",_pathArp="maps/1_AR_CSP.json",_pathSmg="maps/3_SMG.json",_pathSmgp="maps/3_SMG_CSP.json",_pathLmg="maps/9_LMG.json",_pathLmgp="maps/9_LMG_CSP.json",_pathSr="maps/5_SR.json",_pathSrp="maps/5_SR_CSP.json",_pathCar="maps/12_CARBINE.json",_pathCarp="maps/12_CARBINE_CSP.json",_pathExpl="maps/7_EXPLOSIVE.json",_pathExplp="maps/7_EXPLOSIVE_CSP.json",_pathSec="maps/6_PISTOL.json",_pathSecp="maps/6_PISTOL_CSP.json",_pathMelee=
"maps/4_SG.json",_pathMeleep="maps/4_SG_CSP.json";let jsondata,jsondata2,_objAr,_objArp,_objSmg,_objSmgp,_objLmg,_objLmgp,_objSr,_objSrp,_objCar,_objCarp,_objExpl,_objExplp,_objSec,_objSecp,_objMelee,_objMeleep;
const fetchAll=b=>Promise.all(b.map(a=>fetch(a,{method:"GET"}).then(c=>{if(!c.ok)throw Error("Network response was not ok");return c.json()}))),render=()=>{var b=document.getElementById("TypeForm").TypeSelect.value;let a=document.getElementById("WeaponForm").WeaponSelect.value;var c=document.getElementById("ModForm").ModSelect.value;"none"===b?jsondata2=jsondata="none":"graveless"===a||"Helheim"===a||"horizon"===a||"thirdeye"===a||"Coldfang"===a?(jsondata=_objSr,jsondata2=_objArp):"minigun"===a||
"awr"===a?(jsondata=_objExpl,jsondata2=_objLmgp):"AssaultRifle"===b?(jsondata=_objAr,jsondata2=_objArp):"SMG"===b||"Shotgun"===b?(jsondata=_objSmg,jsondata2=_objSmgp):"LMG"===b?(jsondata=_objLmg,jsondata2=_objLmgp):"SniperRifle"===b?(jsondata=_objSr,jsondata2=_objSrp):"Carbine"===b?(jsondata=_objCar,jsondata2=_objCarp):"Special"===b||"Staves"===b?(jsondata=_objExpl,jsondata2=_objExplp):"Secondary"===b?(jsondata=_objSec,jsondata2=_objSecp):"Melee"===b&&(jsondata=_objMelee,jsondata2=_objMeleep);let f=
0,d=0,m=0,h=0,n=0,k=0,l=0,t=b=0,u=0,v=0,x=0,y=0,z=0,p=0,q=0;"none"!==a&&"none"!=jsondata&&("undefined"===typeof jsondata[a].Reload?v=u=f=0:("undefined"===typeof jsondata[a].Reload.Reload_Bullets_Individually?(f=0,document.getElementById("DisplayReloadStyle").textContent=null):!0===jsondata[a].Reload.Reload_Bullets_Individually?(f=1,document.getElementById("DisplayReloadStyle").textContent="/\u767a"):(f=0,document.getElementById("DisplayReloadStyle").textContent=null),u=jsondata[a].Reload.Reload_Amount,
v=jsondata[a].Reload.Reload_Duration),b=()=>{d="undefined"===typeof jsondata[a].Burstfire?20/jsondata[a].Shooting.Delay_Between_Shots:!0===jsondata[a].Burstfire.Enable?20/jsondata[a].Shooting.Delay_Between_Shots*jsondata[a].Burstfire.Shots_Per_Burst:20/jsondata[a].Shooting.Delay_Between_Shots},"undefined"===typeof jsondata[a].Fully_Automatic?b():!0===jsondata[a].Fully_Automatic.Enable?d=jsondata[a].Fully_Automatic.Fire_Rate+4:b(),m="undefined"===typeof jsondata[a].Sneak?0:!0===jsondata[a].Sneak.Enable?
jsondata[a].Sneak.Zoom_Bullet_Spread:0,"undefined"===typeof jsondata[a].Critical_Hits?n=h=0:!0===jsondata[a].Critical_Hits.Enable?(h=jsondata[a].Critical_Hits.Chance/100,n=jsondata[a].Critical_Hits.Bonus_Damage):n=h=0,"undefined"===typeof jsondata[a].Explosions?q=p=0:!0===jsondata[a].Explosions.Enable?(p=jsondata[a].Explosions.Damage_Multiplier,q=jsondata[a].Explosions.Explosion_Radius):q=p=0,"undefined"===typeof jsondata[a].Damage_Based_On_Flight_Time?l=k=0:!0===jsondata[a].Damage_Based_On_Flight_Time.Enable?
0<jsondata[a].Damage_Based_On_Flight_Time.Maximum_Damage&&0<jsondata[a].Damage_Based_On_Flight_Time.Bonus_Damage_Per_Tick?(k=jsondata[a].Damage_Based_On_Flight_Time.Bonus_Damage_Per_Tick/(jsondata[a].Shooting.Projectile_Speed/10)*10,l=jsondata[a].Damage_Based_On_Flight_Time.Maximum_Damage):0>jsondata[a].Damage_Based_On_Flight_Time.Maximum_Damage&&0>jsondata[a].Damage_Based_On_Flight_Time.Bonus_Damage_Per_Tick?(k=jsondata[a].Damage_Based_On_Flight_Time.Bonus_Damage_Per_Tick/(jsondata[a].Shooting.Projectile_Speed/
10)*10,l=jsondata[a].Damage_Based_On_Flight_Time.Maximum_Damage):l=k=0:l=k=0,t="undefined"===typeof jsondata[a].Headshot?0:jsondata[a].Headshot.Bonus_Damage,b="undefined"===typeof jsondata[a].Shooting.Projectile_Damage?0:jsondata[a].Shooting.Projectile_Damage,y="undefined"===typeof jsondata[a].Shooting.Bullet_Spread?0:jsondata[a].Shooting.Bullet_Spread,x=jsondata[a].Shooting.Projectile_Amount,z=jsondata2[a].itemHoldEffects.GunWeight);let A=0,B=0,C=0,w=0,D=0,E=0,r=0;if("none"!==c&&"none"!==a&&"none"!=
jsondata2){let e=null;for(var g in jsondata2[a].Attachments.AttachmentsAffect)e=jsondata2[a].Attachments.AttachmentsAffect[g].split(":"),e[1]===c&&"CAPACITY"===e[0]&&(A=Number(e[2])),e[1]===c&&"RELOAD"===e[0]&&(B=Number(e[2])),e[1]===c&&"GUNWEIGHT"===e[0]&&(C=Number(e[2])),e[1]===c&&"HEADSHOT"===e[0]&&(w=Number(e[2])),e[1]===c&&"FIRERATE"===e[0]&&(D=Number(e[2])),e[1]===c&&"PRESHOOT"===e[0]&&(E=Number(e[2])),e[1]===c&&"DAMAGE"===e[0]&&(r=Number(e[2]))}c=[b,t,u,v,f,d,x,y,m,h,n,k,l,z,p,q];g=[r,w,A,
B,D,E,C];Weapon[5]=c[5];Infinity===Weapon[5]&&(Weapon[5]=20);Result[6]=Math.round((Weapon[5]+g[4])*Math.pow(10,2))/Math.pow(10,2);EnchActive[0]=0===Result[6]||0===EnchDmg[4]?1:1/Math.ceil(EnchDmg[4]*Result[6]);EnchActive[1]=0===Result[6]||0===EnchDmg[5]?1:1/Math.ceil(EnchDmg[5]*Result[6]);CalcAE(b+r,b+t+r+w);Weapon[0]=c[0];Weapon[1]=c[1];Weapon[2]=c[2];Weapon[3]=c[3];Weapon[4]=c[4];Weapon[6]=c[6];Weapon[7]=c[7];Weapon[8]=c[8];Result[12]=c[9]*c[10];Result[13]=c[10];Result[14]=Math.round(c[11]*Math.pow(10,
2))/Math.pow(10,2);Result[15]=c[12];Result[16]=c[14];Result[17]=c[15];Weapon[9]=c[13];Result[0]=Math.round((Weapon[0]+g[0]+EnchDmg[0]*EnchActive[0]+EnchDmg[2]*EnchActive[1]+Ae[0]+Addon[0]+Result[12])*Addon[5]*Math.pow(10,1))/Math.pow(10,1);Result[1]=Math.round((Weapon[0]+g[0]+EnchDmg[0]*EnchActive[0]+EnchDmg[2]*EnchActive[1]+Ae[0]+Addon[0]+Result[12]+Weapon[1]+g[1]+Ae[2])*Addon[5]*Math.pow(10,1))/Math.pow(10,1);Result[2]=Math.round((Weapon[0]+g[0]+EnchDmg[1]+EnchDmg[3]+Ae[1]+Addon[1]+Result[13])*
Addon[5]*Math.pow(10,1))/Math.pow(10,1);Result[3]=Math.round((Weapon[0]+g[0]+EnchDmg[1]+EnchDmg[3]+Ae[1]+Addon[1]+Result[13]+Weapon[1]+g[1]+Ae[2])*Addon[5]*Math.pow(10,1))/Math.pow(10,1);Result[4]=Weapon[2]+g[2]+Addon[2];Result[5]=Weapon[3]+g[3]+Addon[3];Result[7]=Math.round(Result[0]*Result[6]*Math.pow(10,1))/Math.pow(10,1);Result[8]=Math.round(Math.abs(Weapon[7]-g[5])*Math.pow(10,2))/Math.pow(10,2);Result[9]=Math.round(Math.abs(Weapon[8]-g[5])*Math.pow(10,2))/Math.pow(10,2);Result[10]=Math.round((.2+
Weapon[9]+g[6]+Addon[4])/.2*Math.pow(10,2))/Math.pow(10,2);Result[11]=Math.round(Result[4]/Result[6]*Math.pow(10,1))/Math.pow(10,1);Result[18]=Math.round((g[0]+EnchDmg[0]*EnchActive[0]+EnchDmg[2]*EnchActive[1]+Ae[0]+Addon[0]+Result[12])*Addon[5]*Math.pow(10,1))/Math.pow(10,1);Result[19]=Math.round((g[0]+EnchDmg[1]+EnchDmg[3]+Ae[1]+Addon[1]+Result[13])*Addon[5]*Math.pow(10,1))/Math.pow(10,1);document.getElementById("DisplayRate").textContent=Result[6];document.getElementById("DisplayCapacity").textContent=
Result[4];document.getElementById("DisplayReload").textContent=Result[5];document.getElementById("DisplaySpread").textContent=Result[8];document.getElementById("DisplayAdsSpread").textContent=Result[9];document.getElementById("DisplayChangeDmg10m").textContent=Result[14];document.getElementById("DisplayChangeDmgMax").textContent=Result[15];document.getElementById("DisplayWeight").textContent=Result[10];document.getElementById("MobileDisplayRate").textContent=Result[6];document.getElementById("MobileDisplayCapacity").textContent=
Result[4];document.getElementById("MobileDisplayReload").textContent=Result[5];document.getElementById("MobileDisplaySpread").textContent=Result[8];document.getElementById("MobileDisplayAdsSpread").textContent=Result[9];document.getElementById("MobileDisplayChangeDmg10m").textContent=Result[14];document.getElementById("MobileDisplayChangeDmgMax").textContent=Result[15];document.getElementById("MobileDisplayWeight").textContent=Result[10];0<Result[11]?(document.getElementById("DisplayDuration").textContent=
Result[11],document.getElementById("MobileDisplayDuration").textContent=Result[11]):(document.getElementById("DisplayDuration").textContent=0,document.getElementById("MobileDisplayDuration").textContent=0);0<Result[16]?(document.getElementById("DisplayChangeDmgStyle").textContent="\u7206\u767admg",document.getElementById("MobileDisplayChangeDmgStyle").textContent="\u7206\u767admg",document.getElementById("DisplayChangeMaxStyle").textContent="\u7206\u767a\u534a\u5f84",document.getElementById("MobileDisplayChangeMaxStyle").textContent=
"\u7206\u767a\u534a\u5f84",document.getElementById("DisplayChangeDmg10m").textContent=Result[16]+"%",document.getElementById("MobileDisplayChangeDmg10m").textContent=Result[16]+"%",document.getElementById("DisplayChangeDmgMax").textContent=Result[17],document.getElementById("MobileDisplayChangeDmgMax").textContent=Result[17],document.getElementById("DisplayAddDmg").textContent="+"+Result[18]+"("+Result[19]+")",document.getElementById("MobileDisplayAddDmg").textContent="+"+Result[18]+"("+Result[19]+
")"):(0<Result[14]?(document.getElementById("DisplayChangeDmgStyle").textContent="10m\u5897\u5e45",document.getElementById("MobileDisplayChangeDmgStyle").textContent="10m\u5897\u5e45",document.getElementById("DisplayChangeMaxStyle").textContent="\u6700\u5927\u5897\u5e45\u91cf",document.getElementById("MobileDisplayChangeMaxStyle").textContent="\u6700\u5927\u5897\u5e45\u91cf"):(document.getElementById("DisplayChangeDmgStyle").textContent="10m\u6e1b\u8870",document.getElementById("MobileDisplayChangeDmgStyle").textContent=
"10m\u6e1b\u8870",document.getElementById("DisplayChangeMaxStyle").textContent="\u6700\u5927\u6e1b\u8870\u91cf",document.getElementById("MobileDisplayChangeMaxStyle").textContent="\u6700\u5927\u6e1b\u8870\u91cf"),document.getElementById("DisplayChangeDmg10m").textContent=Result[14],document.getElementById("DisplayChangeDmgMax").textContent=Result[15],document.getElementById("MobileDisplayChangeDmg10m").textContent=Result[14],document.getElementById("MobileDisplayChangeDmgMax").textContent=Result[15],
document.getElementById("DisplayAddDmg").textContent=null,document.getElementById("MobileDisplayAddDmg").textContent=null);1<Weapon[6]?(document.getElementById("DisplayPellets").textContent="x"+Weapon[6],document.getElementById("MobileDisplayPellets").textContent="x"+Weapon[6]):(document.getElementById("DisplayPellets").textContent=null,document.getElementById("MobileDisplayPellets").textContent=null);"none"!==a&&"none"!=jsondata?"undefined"===typeof jsondata[a].Shooting.Projectile_Damage?(document.getElementById("DisplayAverageDmg").textContent=
"\u306a\u3057",document.getElementById("DisplayAverageHsDmg").textContent="\u306a\u3057",document.getElementById("DisplayHighestDmg").textContent="\u306a\u3057",document.getElementById("DisplayHighestHsDmg").textContent="\u306a\u3057",document.getElementById("DisplayDps").textContent="\u306a\u3057",document.getElementById("MobileDisplayAverageDmg").textContent="\u306a\u3057",document.getElementById("MobileDisplayAverageHsDmg").textContent="\u306a\u3057",document.getElementById("MobileDisplayHighestDmg").textContent=
"\u306a\u3057",document.getElementById("MobileDisplayHighestHsDmg").textContent="\u306a\u3057",document.getElementById("MobileDisplayDps").textContent="\u306a\u3057"):(document.getElementById("DisplayAverageDmg").textContent=Result[0],document.getElementById("DisplayAverageHsDmg").textContent=Result[1],document.getElementById("DisplayHighestDmg").textContent=Result[2],document.getElementById("DisplayHighestHsDmg").textContent=Result[3],document.getElementById("DisplayDps").textContent=Result[7],document.getElementById("MobileDisplayAverageDmg").textContent=
Result[0],document.getElementById("MobileDisplayAverageHsDmg").textContent=Result[1],document.getElementById("MobileDisplayHighestDmg").textContent=Result[2],document.getElementById("MobileDisplayHighestHsDmg").textContent=Result[3],document.getElementById("MobileDisplayDps").textContent=Result[7]):(document.getElementById("DisplayAverageDmg").textContent=0,document.getElementById("DisplayAverageHsDmg").textContent=0,document.getElementById("DisplayHighestDmg").textContent=0,document.getElementById("DisplayHighestHsDmg").textContent=
0,document.getElementById("DisplayDps").textContent=0,document.getElementById("MobileDisplayAverageDmg").textContent=0,document.getElementById("MobileDisplayAverageHsDmg").textContent=0,document.getElementById("MobileDisplayHighestDmg").textContent=0,document.getElementById("MobileDisplayHighestHsDmg").textContent=0,document.getElementById("MobileDisplayDps").textContent=0)},categorySelect2=document.getElementById("TypeSelect"),subCategorySelect2=document.getElementById("WeaponSelect");
WeaponTypes.forEach(b=>{const a=document.createElement("option");a.textContent=b;categorySelect2.appendChild(a)});
categorySelect2.addEventListener("input",()=>{document.querySelectorAll("#WeaponSelect > option").forEach(a=>a.remove());const b=document.createElement("option");b.textContent="\u6b66\u5668\u3092\u9078\u629e";b.setAttribute("value","none");subCategorySelect2.appendChild(b);subCategorySelect2.disabled=!1;if("blank"==categorySelect2.value)return subCategorySelect2.disabled=!0;WeaponList.forEach(a=>{if(categorySelect2.value==a.category){const c=document.createElement("option");c.textContent=a.name;c.setAttribute("value",
a.value);subCategorySelect2.appendChild(c)}})});
const CalcEnch=()=>{function b(d){"EnchLev1"==c?(EnchDmg[0]=d[0]*d[1],EnchDmg[1]=d[0],EnchDmg[4]=d[4]):"EnchLev2"==c?(EnchDmg[0]=d[0]*d[2],EnchDmg[1]=d[0],EnchDmg[4]=d[4]):"EnchLev3"==c?(EnchDmg[0]=d[0]*d[3],EnchDmg[1]=d[0],EnchDmg[4]=d[4]):(EnchDmg[0]=0,EnchDmg[1]=0,EnchDmg[4]=0)}const a=document.getElementById("EnchantForm").EnchantSelect.value,c=document.getElementById("EnchantForm").EnchantLevSelect.value,f=document.getElementById("FrCheck");"FlexibleResonance"==a?FrLabel.style.display="inline-block":
(FrLabel.style.display="none",f.checked=!1);"ArcaneBrilliance"==a?b(ArcaneBrilliance):"DeathsRuin"==a?b(DeathsRuin):"DemonPower"==a?b(DemonPower):"Evershade"==a?b(Evershade):"FlexibleResonance"==a&&f.checked?b(FlexibleResonance):"ManaFountain"==a?b(ManaFountain):"NightStalker"==a?b(NightStalker):"NorthernWind"==a?b(NorthernWind):"PhoenixFlame"==a?b(PhoenixFlame):"ShadowStrike"==a&&50>enemyManaElem.value?b(ShadowStrike0):"ShadowStrike"==a&&75>enemyManaElem.value?b(ShadowStrike1):"ShadowStrike"==a&&
100>=enemyManaElem.value?b(ShadowStrike2):"ShieldWall"==a?b(ShieldWall):"SiphonLife"==a?b(SiphonLife):"Sunfire"==a?b(Sunfire):"VictoryRush"==a?b(VictoryRush):"ZephyrsBlessing"==a?b(ZephyrsBlessing):(EnchDmg[0]=0,EnchDmg[1]=0,EnchDmg[4]=0);render()},CalcOE=()=>{function b(d){"OeLev1"==c?(EnchDmg[2]=d[0]*d[1],EnchDmg[3]=d[0],EnchDmg[5]=d[4]):"OeLev2"==c?(EnchDmg[2]=d[0]*d[2],EnchDmg[3]=d[0],EnchDmg[5]=d[4]):"OeLev3"==c?(EnchDmg[2]=d[0]*d[3],EnchDmg[3]=d[0],EnchDmg[5]=d[4]):(EnchDmg[2]=0,EnchDmg[3]=
0,EnchDmg[5]=0)}const a=document.getElementById("OeForm").OeSelect.value,c=document.getElementById("OeForm").OeLevSelect.value,f=document.getElementById("OeFrCheck");"FlexibleResonance"==a?OeFrLabel.style.display="inline-block":(OeFrLabel.style.display="none",f.checked=!1);"ArcaneBrilliance"==a?b(ArcaneBrilliance):"DeathsRuin"==a?b(DeathsRuin):"DemonPower"==a?b(DemonPower):"Evershade"==a?b(Evershade):"FlexibleResonance"==a&&f.checked?b(FlexibleResonance):"ManaFountain"==a?b(ManaFountain):"NightStalker"==
a?b(NightStalker):"NorthernWind"==a?b(NorthernWind):"PhoenixFlame"==a?b(PhoenixFlame):"ShadowStrike"==a&&50>enemyManaElem.value?b(ShadowStrike0):"ShadowStrike"==a&&75>enemyManaElem.value?b(ShadowStrike1):"ShadowStrike"==a&&100>=enemyManaElem.value?b(ShadowStrike2):"ShieldWall"==a?b(ShieldWall):"SiphonLife"==a?b(SiphonLife):"Sunfire"==a?b(Sunfire):"VictoryRush"==a?b(VictoryRush):"ZephyrsBlessing"==a?b(ZephyrsBlessing):(EnchDmg[2]=0,EnchDmg[3]=0,EnchDmg[5]=0);render()},CalcAE=(b,a)=>{const c=document.getElementById("AncientEnchantForm").AncientEnchantSelect.value,
f=document.getElementById("BcCheck"),d=document.getElementById("CfCheck"),m=document.getElementById("SdCheck"),h=document.getElementById("WsCheck");"Bloodcraze"==c?BcLabel.style.display="inline-block":(BcLabel.style.display="none",f.checked=!1);"ConcentratedFire"==c?CfLabel.style.display="inline-block":(CfLabel.style.display="none",d.checked=!1);"SuddenDeath"==c?SdLabel.style.display="inline-block":(SdLabel.style.display="none",m.checked=!1);"Windsong"==c?WsLabel.style.display="inline-block":(WsLabel.style.display=
"none",h.checked=!1);"Bloodcraze"==c&&f.checked?(Ae[0]=BcDmg,Ae[1]=BcDmg):"ElementalOverload"==c&&30<myManaElem.value?(Ae[0]=EoDmg,Ae[1]=EoDmg):"Mastercrafted"==c?(Ae[0]=McDmg,Ae[1]=McDmg):"ConcentratedFire"==c&&d.checked?(Ae[0]=CfDmg,Ae[1]=CfDmg):"SuddenDeath"==c&&m.checked?(Ae[0]=SdAverageDmg,Ae[1]=SdHighestDmg):"ManaBurn"==c&&35>=enemyManaElem.value?(Ae[0]=MbDmg,Ae[1]=MbDmg):"Manaflood"==c&&100==myManaElem.value?(Ae[0]=MflDmg2,Ae[1]=MflDmg2):"Manaflood"==c&&75<=myManaElem.value?(Ae[0]=MflDmg1,
Ae[1]=MflDmg1):"Manaflood"==c&&50<=myManaElem.value?(Ae[0]=MflDmg0,Ae[1]=MflDmg0):"EchoOfDeath"==c&&50<=b?(Ae[0]=EodDmg,Ae[1]=EodDmg):"Windsong"==c&&h.checked?(Ae[0]=WsDmg,Ae[1]=WsDmg):(Ae[0]=0,Ae[1]=0);Ae[2]="EchoOfDeath"==c&&50<=a?EodDmg:0},CalcAddon=()=>{const b=document.getElementById("AddonForm").AddonSelect.value,a=document.getElementById("AddonForm").AddonLevSelect.value,c=document.getElementById("SsaCheck"),f=document.getElementById("SbCheck");"SupersonicAmmo"==b?SsaLabel.style.display="inline-block":
(SsaLabel.style.display="none",c.checked=!1);"ShieldBreaker"==b?SbLabel.style.display="inline-block":(SbLabel.style.display="none",f.checked=!1);"ManaPowder"==b?(Addon[2]=0,Addon[3]=0,Addon[4]=0,Addon[5]=1,"AddonLev0"==a?(Addon[0]=MpDmg[0],Addon[1]=MpDmg[0]):"AddonLev1"==a?(Addon[0]=MpDmg[1],Addon[1]=MpDmg[1]):"AddonLev2"==a?(Addon[0]=MpDmg[2],Addon[1]=MpDmg[2]):"AddonLev3"==a?(Addon[0]=MpDmg[3],Addon[1]=MpDmg[3]):(Addon[0]=0,Addon[1]=0)):"HeavyBullets"==b?(Addon[2]=0,Addon[3]=0,Addon[4]=0,Addon[5]=
1,"AddonLev0"==a?(Addon[0]=HbAverageDmg[0],Addon[1]=HbHighestDmg[0]):"AddonLev1"==a?(Addon[0]=HbAverageDmg[1],Addon[1]=HbHighestDmg[1]):"AddonLev2"==a?(Addon[0]=HbAverageDmg[2],Addon[1]=HbHighestDmg[2]):"AddonLev3"==a?(Addon[0]=HbAverageDmg[3],Addon[1]=HbHighestDmg[3]):(Addon[0]=0,Addon[1]=0)):"ExtendedMagazine"==b?(Addon[0]=0,Addon[1]=0,Addon[3]=0,Addon[4]=0,Addon[5]=1,Addon[2]="AddonLev0"==a?EmCapacity[0]:"AddonLev1"==a?EmCapacity[1]:"AddonLev2"==a?EmCapacity[2]:"AddonLev3"==a?EmCapacity[3]:0):
"QuickPull"==b?(Addon[0]=0,Addon[1]=0,Addon[2]=0,Addon[3]=0,Addon[4]=0,Addon[5]=1,Addon[3]="AddonLev0"==a?QpReload[0]:"AddonLev1"==a?QpReload[1]:"AddonLev2"==a?QpReload[2]:"AddonLev3"==a?QpReload[3]:0):"LightweightKit"==b?(Addon[0]=0,Addon[1]=0,Addon[2]=0,Addon[3]=0,Addon[5]=1,Addon[4]="AddonLev0"==a?LkWeight[0]:"AddonLev1"==a?LkWeight[1]:"AddonLev2"==a?LkWeight[2]:"AddonLev3"==a?LkWeight[3]:0):"SupersonicAmmo"==b&&c.checked?(Addon[0]=0,Addon[1]=0,Addon[2]=0,Addon[3]=0,Addon[4]=0,Addon[5]="AddonLev0"==
a?SsaDmg[0]:"AddonLev1"==a?SsaDmg[1]:"AddonLev2"==a?SsaDmg[2]:"AddonLev3"==a?SsaDmg[3]:1):"ShieldBreaker"==b&&f.checked?(Addon[2]=0,Addon[3]=0,Addon[4]=0,Addon[5]=1,"AddonLev0"==a?(Addon[0]=SbDmg[0],Addon[1]=SbDmg[0]):"AddonLev1"==a?(Addon[0]=SbDmg[1],Addon[1]=SbDmg[1]):"AddonLev2"==a?(Addon[0]=SbDmg[2],Addon[1]=SbDmg[2]):"AddonLev3"==a?(Addon[0]=SbDmg[3],Addon[1]=SbDmg[3]):(Addon[0]=0,Addon[1]=0)):(Addon[0]=0,Addon[1]=0,Addon[2]=0,Addon[3]=0,Addon[4]=0,Addon[5]=1);render()};
document.addEventListener("DOMContentLoaded",()=>{fetchAll([_pathAr,_pathArp,_pathSmg,_pathSmgp,_pathLmg,_pathLmgp,_pathSr,_pathSrp,_pathCar,_pathCarp,_pathExpl,_pathExplp,_pathSec,_pathSecp,_pathMelee,_pathMeleep]).then(b=>{[_objAr,_objArp,_objSmg,_objSmgp,_objLmg,_objLmgp,_objSr,_objSrp,_objCar,_objCarp,_objExpl,_objExplp,_objSec,_objSecp,_objMelee,_objMeleep]=b;console.log(b.concat())});document.getElementById("TypeForm").onchange=()=>render();document.getElementById("WeaponForm").onchange=()=>
render();document.getElementById("ModForm").onchange=()=>render();document.getElementById("EnchantForm").onchange=()=>CalcEnch();document.getElementById("OeForm").onchange=()=>CalcOE();document.getElementById("AncientEnchantForm").onchange=()=>render();document.getElementById("AddonForm").onchange=()=>CalcAddon()});
const myManaElem=document.getElementById("myMana"),enemyManaElem=document.getElementById("enemyMana"),myManaValueElem=document.getElementById("myMana-value"),enemyManaValueElem=document.getElementById("enemyMana-value"),setMyManaValue=b=>{myManaValueElem.innerText=b},setEnemyManaValue=b=>{enemyManaValueElem.innerText=b},myManaOnChange=b=>{setMyManaValue(b.target.value);render()},enemyManaOnChange=b=>{setEnemyManaValue(b.target.value);CalcEnch();CalcOE()},EnchCheckOnChange=b=>{CalcEnch()},OeCheckOnChange=
b=>{CalcOE()},AeCheckOnChange=b=>{render()},AddonCheckOnChange=b=>{CalcAddon()};document.getElementById("FrCheck").addEventListener("change",EnchCheckOnChange);document.getElementById("OeFrCheck").addEventListener("change",OeCheckOnChange);document.getElementById("BcCheck").addEventListener("change",AeCheckOnChange);document.getElementById("CfCheck").addEventListener("change",AeCheckOnChange);document.getElementById("SdCheck").addEventListener("change",AeCheckOnChange);
document.getElementById("WsCheck").addEventListener("change",AeCheckOnChange);document.getElementById("SsaCheck").addEventListener("change",AddonCheckOnChange);document.getElementById("SbCheck").addEventListener("change",AddonCheckOnChange);window.onload=()=>{myManaElem.addEventListener("input",myManaOnChange);enemyManaElem.addEventListener("input",enemyManaOnChange);setMyManaValue(myManaElem.value);setEnemyManaValue(enemyManaElem.value)};
